---

- name: Kafka cluster | Initialize servers lists
  set_fact:
    zoo_servers: []
    kafka_zoo_servers: []

- name: Update etc/hosts file with correct entrance
  blockinfile:
    path: /etc/hosts
    block: |
      {% set  kafka_hosts_name = [] %}
      {% if service_prefix is defined %}
      {% set kafka_hosts_name = [service_prefix+'-kafka-'+(id | int + 1 ) | string, service_prefix+'-zoo-'+(id | int + 1 ) | string ] %}
      {% else %}
      {% set kafka_hosts_name = ['kafka'+(id | int + 1 ) | string, 'zoo'+(id | int + 1 ) | string ] %}
      {% endif %}
      {% for host in kafka_hosts_name %}
      {{ ansible_default_ipv4['address'] }} {{ host + '.' + host_domain + ' '+ host if host_domain is defined else host }}
      {% endfor %}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
  loop: "{{ groups['kafka'] }}"
  loop_control:
    index_var: id
  when: configure_etc_hosts
