---
- hosts: centos7
  any_errors_fatal: yes
  pre_tasks:
    - name: Include vars
      include_vars: vars.yml
    - name: Install required package
      yum:
        name: '{{ item }}'
        state: present
        disable_gpg_check: yes
      loop:
        - firewalld
        - epel-release
        - python-pip
    - name: Install docker python package
      pip:
        name: '{{ item }}'
        state: present
      loop:
        - docker
        - docker-compose
  roles:
    - geerlingguy.docker
    - ansible-role-kafka-in-docker

- hosts: ubuntu18
  any_errors_fatal: yes
  pre_tasks:
    - name: Include vars
      include_vars: vars.yml
    - name: Install ufw package
      apt:
        name: '{{ item }}'
        state: present
      loop:
        - ufw
    - name: Install docker python package
      pip:
        name: '{{ item }}'
        state: present
      loop:
        - docker
        - docker-compose
  roles:
    - geerlingguy.docker
    - ansible-role-kafka-in-docker
